/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ConditionalEscrow {
  export type EscrowStruct = {
    depositor: AddressLike;
    beneficiary: AddressLike;
    amountA: BigNumberish;
    amountB: BigNumberish;
    marketId: string;
    expectedOutcomeYes: boolean;
    status: BigNumberish;
    createdAt: BigNumberish;
    beneficiaryAccepted: boolean;
  };

  export type EscrowStructOutput = [
    depositor: string,
    beneficiary: string,
    amountA: bigint,
    amountB: bigint,
    marketId: string,
    expectedOutcomeYes: boolean,
    status: bigint,
    createdAt: bigint,
    beneficiaryAccepted: boolean
  ] & {
    depositor: string;
    beneficiary: string;
    amountA: bigint;
    amountB: bigint;
    marketId: string;
    expectedOutcomeYes: boolean;
    status: bigint;
    createdAt: bigint;
    beneficiaryAccepted: boolean;
  };

  export type UserStatsStruct = {
    totalWon: BigNumberish;
    totalLost: BigNumberish;
    escrowsCreated: BigNumberish;
    escrowsWon: BigNumberish;
    escrowsLost: BigNumberish;
  };

  export type UserStatsStructOutput = [
    totalWon: bigint,
    totalLost: bigint,
    escrowsCreated: bigint,
    escrowsWon: bigint,
    escrowsLost: bigint
  ] & {
    totalWon: bigint;
    totalLost: bigint;
    escrowsCreated: bigint;
    escrowsWon: bigint;
    escrowsLost: bigint;
  };
}

export interface ConditionalEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ESCROW_TIMEOUT"
      | "MAX_USERNAME_LENGTH"
      | "acceptEscrow"
      | "canEmergencyRefund"
      | "createEscrow"
      | "emergencyRefund"
      | "escrowCount"
      | "escrows"
      | "getEscrow"
      | "getEscrows"
      | "getRefundAvailableTime"
      | "getUserEscrows"
      | "getUserStats"
      | "getUsername"
      | "owner"
      | "renounceOwnership"
      | "resolveEscrow"
      | "resolveEscrowBatch"
      | "resolver"
      | "setResolver"
      | "setUsername"
      | "transferOwnership"
      | "usdc"
      | "userStats"
      | "usernames"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCreated"
      | "EscrowRefunded"
      | "EscrowResolved"
      | "OwnershipTransferred"
      | "ResolverUpdated"
      | "UsernameSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ESCROW_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_USERNAME_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canEmergencyRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [AddressLike, BigNumberish, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyRefund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escrows",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrows",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRefundAvailableTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEscrows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUsername",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveEscrow",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveEscrowBatch",
    values: [BigNumberish[], boolean[]]
  ): string;
  encodeFunctionData(functionFragment: "resolver", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setUsername", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ESCROW_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_USERNAME_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canEmergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getEscrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRefundAvailableTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEscrows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveEscrowBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    depositor: AddressLike,
    beneficiary: AddressLike,
    amount: BigNumberish,
    marketId: string,
    expectedOutcomeYes: boolean
  ];
  export type OutputTuple = [
    escrowId: bigint,
    depositor: string,
    beneficiary: string,
    amount: bigint,
    marketId: string,
    expectedOutcomeYes: boolean
  ];
  export interface OutputObject {
    escrowId: bigint;
    depositor: string;
    beneficiary: string;
    amount: bigint;
    marketId: string;
    expectedOutcomeYes: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowRefundedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    depositor: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    escrowId: bigint,
    depositor: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    escrowId: bigint;
    depositor: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowResolvedEvent {
  export type InputTuple = [
    escrowId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    marketResolvedYes: boolean
  ];
  export type OutputTuple = [
    escrowId: bigint,
    recipient: string,
    amount: bigint,
    marketResolvedYes: boolean
  ];
  export interface OutputObject {
    escrowId: bigint;
    recipient: string;
    amount: bigint;
    marketResolvedYes: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverUpdatedEvent {
  export type InputTuple = [oldResolver: AddressLike, newResolver: AddressLike];
  export type OutputTuple = [oldResolver: string, newResolver: string];
  export interface OutputObject {
    oldResolver: string;
    newResolver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UsernameSetEvent {
  export type InputTuple = [user: AddressLike, username: string];
  export type OutputTuple = [user: string, username: string];
  export interface OutputObject {
    user: string;
    username: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConditionalEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): ConditionalEscrow;
  waitForDeployment(): Promise<this>;

  interface: ConditionalEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ESCROW_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  MAX_USERNAME_LENGTH: TypedContractMethod<[], [bigint], "view">;

  acceptEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  canEmergencyRefund: TypedContractMethod<
    [escrowId: BigNumberish],
    [[boolean, string] & { canRefund: boolean; reason: string }],
    "view"
  >;

  createEscrow: TypedContractMethod<
    [
      beneficiary: AddressLike,
      amountA: BigNumberish,
      amountB: BigNumberish,
      marketId: string,
      expectedOutcomeYes: boolean
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyRefund: TypedContractMethod<
    [escrowId: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrowCount: TypedContractMethod<[], [bigint], "view">;

  escrows: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        depositor: string;
        beneficiary: string;
        amountA: bigint;
        amountB: bigint;
        marketId: string;
        expectedOutcomeYes: boolean;
        status: bigint;
        createdAt: bigint;
        beneficiaryAccepted: boolean;
      }
    ],
    "view"
  >;

  getEscrow: TypedContractMethod<
    [escrowId: BigNumberish],
    [ConditionalEscrow.EscrowStructOutput],
    "view"
  >;

  getEscrows: TypedContractMethod<
    [startId: BigNumberish, count: BigNumberish],
    [ConditionalEscrow.EscrowStructOutput[]],
    "view"
  >;

  getRefundAvailableTime: TypedContractMethod<
    [escrowId: BigNumberish],
    [bigint],
    "view"
  >;

  getUserEscrows: TypedContractMethod<
    [user: AddressLike],
    [[bigint[], bigint[]] & { asDepositor: bigint[]; asBeneficiary: bigint[] }],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [ConditionalEscrow.UserStatsStructOutput],
    "view"
  >;

  getUsername: TypedContractMethod<[user: AddressLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveEscrow: TypedContractMethod<
    [escrowId: BigNumberish, marketResolvedYes: boolean],
    [void],
    "nonpayable"
  >;

  resolveEscrowBatch: TypedContractMethod<
    [escrowIds: BigNumberish[], outcomes: boolean[]],
    [void],
    "nonpayable"
  >;

  resolver: TypedContractMethod<[], [string], "view">;

  setResolver: TypedContractMethod<
    [_resolver: AddressLike],
    [void],
    "nonpayable"
  >;

  setUsername: TypedContractMethod<[_username: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userStats: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalWon: bigint;
        totalLost: bigint;
        escrowsCreated: bigint;
        escrowsWon: bigint;
        escrowsLost: bigint;
      }
    ],
    "view"
  >;

  usernames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ESCROW_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_USERNAME_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptEscrow"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canEmergencyRefund"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [[boolean, string] & { canRefund: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      amountA: BigNumberish,
      amountB: BigNumberish,
      marketId: string,
      expectedOutcomeYes: boolean
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyRefund"
  ): TypedContractMethod<[escrowId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "escrowCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        string,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        depositor: string;
        beneficiary: string;
        amountA: bigint;
        amountB: bigint;
        marketId: string;
        expectedOutcomeYes: boolean;
        status: bigint;
        createdAt: bigint;
        beneficiaryAccepted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [escrowId: BigNumberish],
    [ConditionalEscrow.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEscrows"
  ): TypedContractMethod<
    [startId: BigNumberish, count: BigNumberish],
    [ConditionalEscrow.EscrowStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRefundAvailableTime"
  ): TypedContractMethod<[escrowId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserEscrows"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint[], bigint[]] & { asDepositor: bigint[]; asBeneficiary: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [ConditionalEscrow.UserStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUsername"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveEscrow"
  ): TypedContractMethod<
    [escrowId: BigNumberish, marketResolvedYes: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveEscrowBatch"
  ): TypedContractMethod<
    [escrowIds: BigNumberish[], outcomes: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setResolver"
  ): TypedContractMethod<[_resolver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUsername"
  ): TypedContractMethod<[_username: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userStats"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        totalWon: bigint;
        totalLost: bigint;
        escrowsCreated: bigint;
        escrowsWon: bigint;
        escrowsLost: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "usernames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowRefunded"
  ): TypedContractEvent<
    EscrowRefundedEvent.InputTuple,
    EscrowRefundedEvent.OutputTuple,
    EscrowRefundedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowResolved"
  ): TypedContractEvent<
    EscrowResolvedEvent.InputTuple,
    EscrowResolvedEvent.OutputTuple,
    EscrowResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ResolverUpdated"
  ): TypedContractEvent<
    ResolverUpdatedEvent.InputTuple,
    ResolverUpdatedEvent.OutputTuple,
    ResolverUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UsernameSet"
  ): TypedContractEvent<
    UsernameSetEvent.InputTuple,
    UsernameSetEvent.OutputTuple,
    UsernameSetEvent.OutputObject
  >;

  filters: {
    "EscrowCreated(uint256,address,address,uint256,string,bool)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowRefunded(uint256,address,uint256,string)": TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;
    EscrowRefunded: TypedContractEvent<
      EscrowRefundedEvent.InputTuple,
      EscrowRefundedEvent.OutputTuple,
      EscrowRefundedEvent.OutputObject
    >;

    "EscrowResolved(uint256,address,uint256,bool)": TypedContractEvent<
      EscrowResolvedEvent.InputTuple,
      EscrowResolvedEvent.OutputTuple,
      EscrowResolvedEvent.OutputObject
    >;
    EscrowResolved: TypedContractEvent<
      EscrowResolvedEvent.InputTuple,
      EscrowResolvedEvent.OutputTuple,
      EscrowResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ResolverUpdated(address,address)": TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;
    ResolverUpdated: TypedContractEvent<
      ResolverUpdatedEvent.InputTuple,
      ResolverUpdatedEvent.OutputTuple,
      ResolverUpdatedEvent.OutputObject
    >;

    "UsernameSet(address,string)": TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
    UsernameSet: TypedContractEvent<
      UsernameSetEvent.InputTuple,
      UsernameSetEvent.OutputTuple,
      UsernameSetEvent.OutputObject
    >;
  };
}
